# Generated by Django 6.0.3 on 2026-03-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('header_title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('sub_text', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_name', models.CharField(blank=True, max_length=150, null=True)),
                ('signature_role', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTemplateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_app.certificatetemplate')),
            ],
        ),
    ]
