# Generated by Django 6.0.3 on 2026-04-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='eligible_for_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='result',
            field=models.CharField(default='Failed', max_length=50),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
