# Generated by Django 6.0.3 on 2026-04-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examinvitation_sent_at_examsubmission_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
