# Generated by Django 6.0.3 on 2026-04-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_finalproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='template',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
