# Generated by Django 6.0.3 on 2026-04-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('course_title', models.CharField(max_length=200)),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Issued', max_length=50)),
            ],
        ),
    ]
