# Generated by Django 6.0.3 on 2026-04-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
